config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :file_methods do
  member do
    get "vote"
  end
end

  resources :file_instances do
  member do
    get "vote"
  end
end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/file_instance.rb
class FileInstance < ActiveRecord::Base
  has_many :file_methods
  acts_as_votable 
end

app/controllers/file_instances_controller.rb
class FileInstancesController < ApplicationController
  before_action :set_file_instance, only: [:show, :edit, :update, :destroy, :vote]

  # GET /file_instances
  # GET /file_instances.json
  def index
    @file_instances = FileInstance.all
  end

  # GET /file_instances/1
  # GET /file_instances/1.json
  def show
  end

  # GET /file_instances/new
  def new
    @file_instance = FileInstance.new
  end

  # GET /file_instances/1/edit
  def edit
  end

  # POST /file_instances
  # POST /file_instances.json
  def create
    @file_instance = FileInstance.new(file_instance_params)

    respond_to do |format|
      if @file_instance.save
        format.html { redirect_to @file_instance, notice: 'File instance was successfully created.' }
        format.json { render :show, status: :created, location: @file_instance }
      else
        format.html { render :new }
        format.json { render json: @file_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /file_instances/1
  # PATCH/PUT /file_instances/1.json
  def update
    respond_to do |format|
      if @file_instance.update(file_instance_params)
        format.html { redirect_to @file_instance, notice: 'File instance was successfully updated.' }
        format.json { render :show, status: :ok, location: @file_instance }
      else
        format.html { render :edit }
        format.json { render json: @file_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_instances/1
  # DELETE /file_instances/1.json
  def destroy
    @file_instance.destroy
    respond_to do |format|
      format.html { redirect_to file_instances_url, notice: 'File instance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @file_instance.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_instance
      @file_instance = FileInstance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_instance_params
      params.require(:file_instance).permit(:file_type, :name, :description, :id, :user_id)
    end
end

app/helpers/file_instances_helper.rb
module FileInstancesHelper
end

app/views/file_instances/_form.html.erb
<%= form_for(@file_instance) do |f| %>
  <% if @file_instance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_instance.errors.count, "error") %> prohibited this file_instance from being saved:</h2>

      <ul>
      <% @file_instance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_type %><br>
    <%= f.number_field :file_type %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/file_instances/edit.html.erb
<h1>Editing file_instance</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_instance %> |
<%= link_to 'Back', file_instances_path %>

app/views/file_instances/index.html.erb
<h1>Listing file_instances</h1>

<table>
  <thead>
    <tr>
      <th>File type</th>
      <th>Name</th>
      <th>Description</th>
      <th>Id</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @file_instances.each do |file_instance| %>
      <tr>
        <td><%= file_instance.file_type %></td>
        <td><%= file_instance.name %></td>
        <td><%= file_instance.description %></td>
        <td><%= file_instance.id %></td>
        <td><%= file_instance.user_id %></td>
        <td><%= link_to 'Show', file_instance %></td>
        <td><%= link_to 'Edit', edit_file_instance_path(file_instance) %></td>
        <td><%= link_to 'Destroy', file_instance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File instance', new_file_instance_path %>

app/views/file_instances/new.html.erb
<h1>New file_instance</h1>

<%= render 'form' %>

<%= link_to 'Back', file_instances_path %>

app/views/file_instances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File type:</strong>
  <%= @file_instance.file_type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @file_instance.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @file_instance.description %>
</p>

<p>
  <strong>Id:</strong>
  <%= @file_instance.id %>
</p>

<p>
  <strong>User:</strong>
  <%= @file_instance.user_id %>
</p>

<%= link_to 'Edit', edit_file_instance_path(@file_instance) %> |
<%= link_to 'Back', file_instances_path %>