config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :file_methods do
  member do
    get "vote"
  end
end

  resources :file_instances do
  member do
    get "vote"
  end
end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/file_method.rb
class FileMethod < ActiveRecord::Base
  belongs_to :file_instance
  acts_as_votable 
end

app/controllers/file_methods_controller.rb
class FileMethodsController < ApplicationController
  before_action :set_file_method, only: [:show, :edit, :update, :destroy, :vote]

  # GET /file_methods
  # GET /file_methods.json
  def index
    @file_methods = FileMethod.all
  end

  # GET /file_methods/1
  # GET /file_methods/1.json
  def show
  end

  # GET /file_methods/new
  def new
    @file_method = FileMethod.new
  end

  # GET /file_methods/1/edit
  def edit
  end

  # POST /file_methods
  # POST /file_methods.json
  def create
    @file_method = FileMethod.new(file_method_params)

    respond_to do |format|
      if @file_method.save
        format.html { redirect_to @file_method, notice: 'File method was successfully created.' }
        format.json { render :show, status: :created, location: @file_method }
      else
        format.html { render :new }
        format.json { render json: @file_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /file_methods/1
  # PATCH/PUT /file_methods/1.json
  def update
    respond_to do |format|
      if @file_method.update(file_method_params)
        format.html { redirect_to @file_method, notice: 'File method was successfully updated.' }
        format.json { render :show, status: :ok, location: @file_method }
      else
        format.html { render :edit }
        format.json { render json: @file_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_methods/1
  # DELETE /file_methods/1.json
  def destroy
    @file_method.destroy
    respond_to do |format|
      format.html { redirect_to file_methods_url, notice: 'File method was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @file_method.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_method
      @file_method = FileMethod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_method_params
      params.require(:file_method).permit(:id, :created_by, :name, :description, :input, :output, :file_instance_id)
    end
end

app/helpers/file_methods_helper.rb
module FileMethodsHelper
end

app/views/file_methods/_form.html.erb
<%= form_for(@file_method) do |f| %>
  <% if @file_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_method.errors.count, "error") %> prohibited this file_method from being saved:</h2>

      <ul>
      <% @file_method.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.number_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :input %><br>
    <%= f.text_area :input %>
  </div>
  <div class="field">
    <%= f.label :output %><br>
    <%= f.text_area :output %>
  </div>
  <div class="field">
    <%= f.label :file_instance_id %><br>
    <%= f.text_field :file_instance_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/file_methods/edit.html.erb
<h1>Editing file_method</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_method %> |
<%= link_to 'Back', file_methods_path %>

app/views/file_methods/index.html.erb
<h1>Listing file_methods</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Created by</th>
      <th>Name</th>
      <th>Description</th>
      <th>Input</th>
      <th>Output</th>
      <th>File instance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @file_methods.each do |file_method| %>
      <tr>
        <td><%= file_method.id %></td>
        <td><%= file_method.created_by %></td>
        <td><%= file_method.name %></td>
        <td><%= file_method.description %></td>
        <td><%= file_method.input %></td>
        <td><%= file_method.output %></td>
        <td><%= file_method.file_instance %></td>
        <td><%= link_to 'Show', file_method %></td>
        <td><%= link_to 'Edit', edit_file_method_path(file_method) %></td>
        <td><%= link_to 'Destroy', file_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File method', new_file_method_path %>

app/views/file_methods/new.html.erb
<h1>New file_method</h1>

<%= render 'form' %>

<%= link_to 'Back', file_methods_path %>

app/views/file_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @file_method.id %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @file_method.created_by %>
</p>

<p>
  <strong>Name:</strong>
  <%= @file_method.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @file_method.description %>
</p>

<p>
  <strong>Input:</strong>
  <%= @file_method.input %>
</p>

<p>
  <strong>Output:</strong>
  <%= @file_method.output %>
</p>

<p>
  <strong>File instance:</strong>
  <%= @file_method.file_instance %>
</p>

<%= link_to 'Edit', edit_file_method_path(@file_method) %> |
<%= link_to 'Back', file_methods_path %>